### PR TITLE
Support transactions

### PR DESCRIPTION
**Pull request by johnnyshields**

### CODE REVIEW

**Comment by dblock** [comment]
👀 I see you really went at it @johnnyshields, good stuff ;)

**Comment by johnnyshields** [comment]
Yes, I did. I think I've come up with pretty good logic at this point, am using threads in the tests to check simultaneous actions for various scenarios (add, change scope, etc.)

**Comment by dblock** [comment]
> Yes, I did. I think I've come up with pretty good logic at this point, am using threads in the tests to check simultaneous actions for various scenarios (add, change scope, etc.)

I did a cursory look at the code and I think it's a net "a lot better". Good call on dropping older MongoDB support as well and just moving forward. Either way if it doesn't work correctly we can blame all data loss on MongoDB again ;)

**Comment by johnnyshields** [comment]
Main reason for dropping older Mongoid is that this gem really should only be used in production with transactions enabled, and I don't think they work before Mongoid 7. I've just pushed version 6.0.0 to Rubygems by the way, please give it a try.

**Pull request closed without merging**
